### ISSUE TITLE
Allow to disable zip compression when creating a SIP

### ISSUE THREAD

**Issue by yonnycardenas** [keeps/commons-ip#125]
Currently the CLI makes always a zip compression and file packaging when creating a SIP, it would be great to have the ability to disable it. Saving the SIP to flat directory allows to use other compression options or tools such as TAR.

**Comment by ThomasEdvardsen** [comment]
This also applies to those cases where you use commons-ip as a java library. I would like to be able to choose between no packaging, ZIP packaging and TAR packaging. But as a start, the option to choose no packaging is most important to me.

**Comment by hmiguim** [comment]
A new CLI option was added to choose the write strategy to be used: ZIP or Folder. The default option is ZIP.
