### ISSUE TITLE
Java 8 compatibility with javax library when handling SIPs with URL encoded characters

### ISSUE THREAD

**Issue by hmiguim** [keeps/commons-ip#136]
Example:

Filename: PT%2FPT-KEEPS%2FLevel-1%2FLevel-2.zip

Running this code with Java 8 produces an error because the Unmarshaller decode the %2F instead of keeping it.

https://github.com/keeps/commons-ip/blob/b57974301447d49dd6486ea87258b131ef5262af/src/main/java/org/roda_project/commons_ip2/utils/METSUtils.java#L62

**Comment by luis100** [comment]
Related to #117

**Comment by hmiguim** [comment]
Fix on version [2.3.2](https://github.com/keeps/commons-ip/releases/tag/2.3.2)
