### ISSUE TITLE
METS XML not valid when adding file with filename containing some characters

### ISSUE THREAD

**Issue by sleroux-keep** [keeps/commons-ip#14]
> URIs require that some characters be escaped with their hexadecimal Unicode code point preceded by the % character. This includes non-ASCII characters and some ASCII characters, namely control characters, spaces, and the following characters (unless they are used as deliimiters in the URI): <>#%{}|\^`. For example, ../édition.html must be represented instead as ../%C3%A9dition.html, with the é escaped as %C3%A9. However, the anyURI type will accept these characters either escaped or unescaped. With the exception of the characters % and #, it will assume that unescaped characters are intended to be escaped when used in an actual URI, although the schema processor will do nothing to alter them. It is valid for an anyURI value to contain a space, but this practice is strongly discouraged. Spaces should instead be escaped using %20."

http://www.datypic.com/sc/xsd/t-xsd_anyURI.html

`
Representation METS.xml file is not valid.javax.xml.bind.UnmarshalException - with linked exception: [org.xml.sax.SAXParseException; systemId: file:/tmp/ID14016b07-9bac-4d96-806c-9c47d57fa26c/representations/rep1/METS.xml; lineNumber: 10; columnNumber: 106; cvc-datatype-valid.1.2.1: 'data/1__#$!@%!#__unknown.jpg' is not a valid value for 'anyURI'.]
`

**Comment by sleroux-keep** [comment]
Fixed @ 4b30fc678d21f9ad6101f3aa5d4329a47a12737f .

**Comment by sleroux-keep** [comment]
I didn't want to add the encode/decode outside of mets classes... When updating mets, the same "fix" to the beans classes needs to be done.

**Comment by hsilva-keep** [comment]
Fixed since fdeacc1fc1ae238af95cdb9ca2c28ba3ea5228a7. 
Some changes were necessary (to commit 4b30fc678d21f9ad6101f3aa5d4329a47a12737f)  to make sure this is a long term solution (as POJOs generated from .xsd might get overwritten).
