### ISSUE TITLE
Validation module: CSIP20 - difference in modality levels?

### ISSUE THREAD

**Issue by PhillipAasvangTommerholt** [keeps/commons-ip#158]
The [testCase.xml ](https://github.com/DILCISBoard/eark-ip-test-corpus/blob/integration/corpora/csip/metadata/dmdsec/CSIP20/testCase.xml) lists different scenarios.

If the @STATUS attribute doesn’t exist in the METS.xml, then it is indeed a SHOULD as the CSIP states. But if it does exist, then the test corpus team argues that the CSIP is to bo read in the manner that the value in the @STATUS attribute MUST be taken from the vocabulary, making this a specific extra test with a “MUST” modality.
See package  https://github.com/DILCISBoard/eark-ip-test-corpus/blob/integration/corpora/csip/metadata/dmdsec/CSIP20/IP_18000_CSIP20_2.zip and  https://github.com/DILCISBoard/eark-ip-test-corpus/blob/integration/corpora/csip/metadata/dmdsec/CSIP20/IP_18000_CSIP20_3.zip

**Comment by AntonioG70** [comment]
The CSIP20 specification currently considers it to be "SHOULD" and does not mandate a change in level to "MUST" when the @STATUS attribute is present. To implement the changes you have proposed, an update to the specification itself would be required so that it could be more specific about this case.

**Comment by prettybits** [comment]
@AntonioG70 Looking at how the current validation for CSIP20 is [implemented](https://github.com/keeps/commons-ip/blob/7ffefe7c1d5e373c6323ed606bfb2a696405fe3e/src/main/java/org/roda_project/commons_ip2/validator/component/descriptiveMetadataComponent/DescriptiveMetadataComponentValidator.java#L419) the value of the `@STATUS` attribute is already validated against the vocabulary. The description for the requirement also says "[...] using a fixed vocabulary", do you think more clarity is still needed still?

On the other hand there is an issue there that a missing `@STATUS` attribute is treated as failure even though it's defined as SHOULD.
