### ISSUE TITLE
SIP2 validation checks against wrong profile

### ISSUE THREAD

**Issue by prettybits** [keeps/commons-ip#161]
When validating an E-ARK SIP with `mets/@PROFILE` set to `https://earksip.dilcis.eu/profile/E-ARK-SIP.xml` as specified in SIP2 I get a validation failure for the requirement:

```json
{
    "specification" : "SIP-2.0.4",
    "id" : "SIP2",
    "name" : "METS Profile",
    "location" : "mets/@PROFILE",
    "description" : "The value is set to “https://earksip.dilcis.eu/profile/E-ARK-SIP.xml”.",
    "cardinality" : "1..1",
    "level" : "MUST",
    "testing" : {
      "outcome" : "FAILED",
      "issues" : [ "mets/@PROFILE value isn't https://earkcsip.dilcis.eu/profile/E-ARK-CSIP.xml /home/prettybits/SIPs/SIP2/representations/master/METS.xml" ],
      "warnings" : [ ],
      "notes" : [ ]
}
```

Also, it looks like only errors for the representation METS are reported, even though the package METS has the same profile set?

**Comment by AntonioG70** [comment]
Hello,

Could you please send the SIP you used?

**Comment by prettybits** [comment]
Sure, find a minimal SIP to reproduce the issue [here](https://github.com/keeps/commons-ip/files/11881427/uuid-F353033C-CE32-46F8-9B77-F3A2A372BE30.tar.gz)
