### ISSUE TITLE
XLink type validation fails when METS elements are in prefixed namespace

### ISSUE THREAD

**Issue by prettybits** [keeps/commons-ip#162]
Validations for the presence of an `@xlink:type="simple"` attribute fail even when the attributes are actually there when METS documents use a prefix for the METS namespace (i.e. `mets:mets/[@xmlns:mets="http://www.loc.gov/METS/"]`) instead of the default namespace.

Affected requirements: CSIP23, CSIP37, CSIP50, CSIP78 and CSIP111

The issue description of a failure then still refers to an issue with the attribute even though that has no relation to the cause which I suspect may be due to not using local names for element name checks somewhere?

For example this `dmdSec`:

```xml
<mets:dmdSec ID="MODS" CREATED="2023-06-26T07:30:30Z" STATUS="CURRENT">
    <mets:mdRef ID="uuid-aa82b773-dcb9-48ca-a0d2-dcbadfef2622" LOCTYPE="URL" MDTYPE="MODS" MIMETYPE="text/xml" CHECKSUMTYPE="SHA-256" xlink:type="simple" xlink:href="metadata/descriptive/MODS.xml" SIZE="2987" CREATED="2023-06-26T07:30:30.855950Z" CHECKSUM="C40D22CFED362AC173565A05B059120E8C9BAE3FD7B087FAACC643849455394C" />
</mets:dmdSec>
```

misleadingly fails with

```json
{
    "specification" : "CSIP-2.0.4",
    "id" : "CSIP23",
    "name" : "Type of link",
    "location" : "mets/dmdSec/mdRef[@xlink:type=’simple’]",
    "description" : "Attribute used with the value “simple”. Value list is maintained by the xlink standard.",
    "cardinality" : "1..1",
    "level" : "MUST",
    "testing" : {
      "outcome" : "FAILED",
      "issues" : [ "mets/dmdSec/mdRef[@xlink:type=’simple’] in Root METS.xml can't be null" ],
      "warnings" : [ ],
      "notes" : [ ]
    }
  }
```

**Comment by carlosjepard** [comment]
Hi!
Can you provide me with a SIP file that presents this behaviour?

**Comment by prettybits** [comment]
Hi @carlosjepard ,
you can find a SIP that exhibits most of the requirement failures reported in this issue [here](https://github.com/keeps/commons-ip/files/11894322/uuid-F353033C-CE32-46F8-9B77-F3A2A372BE31.zip).

I haven't been able to limit the SIP to _only_ these failures, e.g. CSIP88 also fails with this package as reported in another issue. CSIP111 I would have expected to also fail here analogously, there might be something else hiding the issue?
