### ISSUE TITLE
CSIP88 validation fails despite correctly labeled metadata div

### ISSUE THREAD

**Issue by prettybits** [keeps/commons-ip#165]
With descriptive metadata being present and referenced, and a `mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Metadata']` present like required by CSIP88 validation fails with

```json
{
    "specification" : "CSIP-2.0.4",
    "id" : "CSIP88",
    "name" : "Metadata division",
    "location" : "mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Metadata']",
    "description" : "The metadata referenced in the administrative and/or descriptive metadata section is described in the structural map with one sub division.When the transfer consists of only administrative and/or descriptive metadata this is the only sub division that occurs.",
    "cardinality" : "1..1",
    "level" : "MUST",
    "testing" : {
      "outcome" : "FAILED",
      "issues" : [ "You have metadata files, must add mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Metadata'] in Root METS.xml" ],
      "warnings" : [ ],
      "notes" : [ ]
    }
}
```

I see there was a related issue #54 which [changed](https://github.com/keeps/commons-ip/commit/52b99fe7ca91f08128b9311f7cb4a1afc2f8eb4b#diff-869153069bd2d62c4cd5e6b54a8da4c7a6480818828280632369cc5600c39f14L626) the related logic to fail when the div with the required label is found?

**Comment by carlosjepard** [comment]
Hello! I tested this verification with the file you provided on issue #162,  which has a struct map that fits the parameters of this verification... However, this verification passes. Can you provide me with a Sip file that fails this verification?

**Comment by prettybits** [comment]
Hi @carlosjepard ,
you're right, sorry, I was testing this with a local version that still had adjustments to fix another preceding issue and missed that I wasn't testing an unmodified version. Although now with the file I provided that you also tested with I actually get a null pointer exception during CSIP86 validation of the package METS:

```
Exception in thread "main" java.lang.NullPointerException
        at org.roda_project.commons_ip2.validator.component.structuralMapComponent.StructuralMapComponentValidator.validateCSIP86(StructuralMapComponentValidator.java:615)
        at org.roda_project.commons_ip2.validator.component.structuralMapComponent.StructuralMapComponentValidator.validate(StructuralMapComponentValidator.java:92)
        at org.roda_project.commons_ip2.validator.EARKSIPValidator.validateComponents(EARKSIPValidator.java:183)
        at org.roda_project.commons_ip2.validator.EARKSIPValidator.validateRootMets(EARKSIPValidator.java:275)
        at org.roda_project.commons_ip2.validator.EARKSIPValidator.validate(EARKSIPValidator.java:159)
        at org.roda_project.commons_ip2.validator.CLI.CLIValidator.validate(CLIValidator.java:213)
        at org.roda_project.commons_ip2.validator.CLI.CLIValidator.start(CLIValidator.java:157)
        at org.roda_project.commons_ip2.validator.CLI.Main.main(Main.java:30)
```

which is what I had quickly adjusted during my testing, e.g. for this case [here](https://github.com/keeps/commons-ip/blob/master/src/main/java/org/roda_project/commons_ip2/validator/component/structuralMapComponent/StructuralMapComponentValidator.java#L615C13-L615C57), which checks for `div.getLABEL().equals("CSIP")` (as is done in a few other places in that file). My SIPs generally don't have a label on the first division as that requirement has been deprecated with version 2.1.0 of the specification. As mentioned in #166 this actually seems expected? Is it intended to officially support the newest version of the spec at some point?

I created a new SIP that should show the CSIP88 issue [here](https://github.com/keeps/commons-ip/files/11906536/uuid-F353033C-CE32-46F8-9B77-F3A2A372BE32.zip), although there I had to adjust the labels on the first div to "CSIP" to fit the checks actually being done, even though the deprecated rule wants the same value as the `mets/@OBJID`, leading to CSIP86 also failing.

Besides all that, I'm wondering why you don't seem to have run into the same exception during your testing, strange.
