### ISSUE TITLE
Wrong value for "specification" field in validation report for CSIP72-79

### ISSUE THREAD

**Issue by prettybits** [keeps/commons-ip#166]
Report entries for all requirements from CSIP72 through to CSIP79 put "CSIP72" for the `specification` field instead of "CSIP-2.0.4" like the rest of them, e.g.:

```json
{
    "specification" : "CSIP72",
    "id" : "CSIP79",
    "name" : "Resource location",
    "location" : "mets/fileSec/fileGrp/file/FLocat/@xlink:href",
    "description" : "The actual location of the resource. We recommend recording a URL type filepath within this attribute.",
    "cardinality" : "1..1",
    "level" : "MUST",
    "testing" : {
      "outcome" : "PASSED",
      "issues" : [ ],
      "warnings" : [ ],
      "notes" : [ ]
    }
}
```

Should these be changed to "CSIP-2.1.0" eventually? Is the current implementation meant to be compliant to the current version of the spec or is 2.0.4 still the intended target?

**Comment by AntonioG70** [comment]
Hi,
The current implementation uses the 2.0.4 specification.

**Comment by luis100** [comment]
This actually should be a matter of discussion. Currently, an E-ARK SIP does not state for which version of the specification it is supposed to be valid against. 

1. Should we always validate against the latest version of the specification? 
2. Should we be able to set against which version are we validating and default to the latest if nothing is stated? 
3. Can a SIP be valid against 2.0.4 but not 2.1.0? What about the other way around? 
4. Should an archive be able to state that it only supports E-ARK SIP 2.0.4 but not a higher or lower version?
5. What about major versions? E-ARK SIP v1.X is certainly not compatible with E-ARK SIP v2.0 nor the other way around there should be a clear strategy to state which major version is an E-ARK SIP compatible with, without the need of user intervention or extraneous information or guessing by the attributes and elements.

**Comment by prettybits** [comment]
> Currently, an E-ARK SIP does not state for which version of the specification it is supposed to be valid against.

I was just thinking the same, it would be a good idea to have some explicit marker for the targeted specification version somewhere, as well as having the METS profiles referenced via a URL path that includes the version (the SIP/AIP/DIP profiles themselves would also need to take care to use a versioned URL in their `related_profile` element). Do you want to open an issue in the specification repo for this?

My personal answers to your points would be:

1. Given that the METS profile referenced on the root element currently always resolves to the latest version of the document due to no versioned path being available to my knowledge I think that the validation should adhere to the (latest) version of the spec stated there, i.e. 2.1.0 at the moment.
2. I think in general having a way to explicitly specify the version to validate against (possibly overriding the version stated in the METS document once that possibility exists) is a nice thing to have, depending on the implementation complexity and maintenance costs that comes with that.
3. As far as I'm aware of the changes this mainly (only?) revolves around CSIP86, so a SIP that's valid against 2.0.4 should be valid against 2.1.0 as well, but not necessarily the other way around, depending on whether the top-level retains a label equivalent to the `OBJID` or not.
4. As there doesn't seem to be a guarantee for backward compatibility between versions I would say yes.
5. Not sure what could be done there realistically, if E-ARK v1 SIPs/DIPs are actively being exchanged already I think there would have to be some amount of guessing unless the respective systems would add some additional info outside the package itself to disambiguate during transfer.
