### ISSUE TITLE
Add support for E-ARK AIP

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/commons-ip#18]
- [ ] Create EARKAIP class (`public class EARKAIP extends AIP`) & implement necessary methods (besides abstract methods, implement static methods `public static AIP parse(Path source) throws ParseException` & `public static AIP parse(Path source, Path destinationDirectory) throws ParseException`)
- [ ] Create a new method in the AIP abstract class to just generate the METS files (1 for the whole package + 1 per each representation)

**Comment by rui-castro** [comment]
@hsilva-keep I can't find the `AIP` class. Where is it?

**Comment by hsilva-keep** [comment]
@rui-castro https://github.com/keeps/commons-ip/blob/master/src/main/java/org/roda_project/commons_ip/model/AIP.java???

**Comment by rui-castro** [comment]
@hsilva-keep done in PR #20

**Comment by rui-castro** [comment]
@hsilva-keep the support to read agents from RODA AIP is missing. Can you provide an example of a RODA AIP with agent information?

**Comment by hsilva-keep** [comment]
@rui-castro code was merged, with some fixes & improvements into version alpha25 (0149a8bd60b14c09a388cac1201507500169ccca) & it looks ok. The question about agents in RODA should be placed in the issue related with using commons-ip in RODA to process RODA AIP into RODA E-ARK & vice versa.
