### ISSUE TITLE
CSIP106 validation fails due to ID not being unique across Package and Representation METS

### ISSUE THREAD

**Issue by prettybits** [keeps/commons-ip#180]
When an SIP uses the same identifier in the Package and a Representation METS (while being unique within the documents), validation for CSIP106 fails with the following result:

```json
{
    "specification" : "CSIP-2.0.4",
    "id" : "CSIP106",
    "name" : "Representations division identifier",
    "location" : "mets/structMap[@LABEL='CSIP']/div/div/@ID",
    "description" : "Mandatory, xml:id identifier must be unique within the package.",
    "cardinality" : "1..1",
    "level" : "MUST",
    "testing" : {
      "outcome" : "FAILED",
      "issues" : [ "Value PHYS_0000 in /home/prettybits/SIPs/CSIP106/representations/ocr-txt/METS.xml for mets/structMap[@LABEL='CSIP']/div/div/@ID isn't unique in the package" ],
      "warnings" : [ ],
      "notes" : [ ]
    }
```

I posted a [request for clarification](https://github.com/DILCISBoard/E-ARK-CSIP/issues/702) on the intended scope of identifier uniqueness in the CSIP repo and refrained from opening an issue here at first, but I think having an issue for discussion here as well doesn't hurt.

By the reasoning I gave in the specification issue and because the descriptions all specifically talk about `xml:id` identifiers I'd say nothing more than intra-document uniqueness is really intended here and also see no technical reason for having these identifiers be unique across documents. With that interpretation the schema validation alone would also already catch any issues and no further validation for uniqueness would need to be done.

**Comment by prettybits** [comment]
@luis100 @hmiguim 

It [sounds](https://github.com/DILCISBoard/E-ARK-CSIP/issues/702#issuecomment-1641880041) like my interpretation here was correct and identifiers only need to be unique within the METS documents (and thus are already covered by XML schema validation). The validation of the related rules would therefore need to be adjusted.

**Comment by luis100** [comment]
Yes, I agree. We will add this issue to the roadmap.
