### ISSUE TITLE
New optional param to add metadata schema file

### ISSUE THREAD

**Issue by MartinR4838** [keeps/commons-ip#186]
Hi,

just an idea, not a real issue. 

It can be useful to add param like -ms or --metadata-schema, [OPTIONAL] Path to a metadata xsd schema. Such schema file belongs to /schemas folder. 

Best regards
Martin

**Comment by prettybits** [comment]
Hi @MartinR4838, this is already being worked on in #183, currently with `-sh` or `--metadata-schema` arguments. I also proposed to use a `-ms` short option instead there.

**Comment by MartinR4838** [comment]
Thanks, 

I apologize for carrying the owls to Athens :-).
Best

**Comment by jmaferreira** [comment]
Duplicates #183
