### ISSUE TITLE
Add a way to get the current progress of the SIP's creation

### ISSUE THREAD

**Issue by adrapereira** [keeps/commons-ip#2]
In RODA-In, when exporting SIPs, the UI shows the estimated remaining time for the exportation. I need a way to know the progress of the SIP creation to be able to compute this estimate.

This should be very detailed, for example, when there's a file copy I should be able to know how much of the file has been copied. The approach to only update the progress after every file copy, or after each task has been completed (data copy, metadata copy, etc.), can't be applied because it doesn't give enough information when the SIP has very large files.

**Comment by hsilva-keep** [comment]
Since 1a824e9ac560fd17c3903e95a2695ce686076e13 / alpha5, you may implement SIPObserver interface, register youself as an SIP observer and receive notifications of the build process (for the moment notifications sent are related with the ZIP creation only).
