### ISSUE TITLE
spelling error at README.md for short option submitter-agent-name

### ISSUE THREAD

**Issue by alex00111111** [keeps/commons-ip#202]
The example at:
https://github.com/keeps/commons-ip/blob/c1ab604340e6806ecbd0f5895855dca1ec4ed123/README.md?plain=1#L84C77-L84C77

says: `-sn agent1` 

correct would be  `-san agent1`

**Comment by hmiguim** [comment]
Hi @alex00111111,

With the release of https://github.com/keeps/commons-ip/releases/tag/2.5.0 we clean-up the commaline interface and follow more deeply the CLI standards. Submitter agent name short parameter was removed in favor of the longer parameter.
