### ISSUE TITLE
Commons-ip fails when creating Geospatial

### ISSUE THREAD

**Issue by MartinR4838** [keeps/commons-ip#203]
Hi, 

when playing with commons-ip, I´ve encountered bug when jar file fails. I presume it´s coused by space in package type label. Mixed works fine but Geospatial Data not. There are more labels containing space in CSIP content categories [https://[earkcsip.dilcis.eu/schema/CSIPVocabularyContentCategory.xml](https://earkcsip.dilcis.eu/schema/CSIPVocabularyContentCategory.xml)](url)

Best regards
M.

**Comment by luis100** [comment]
Hello, do you have any additional details, as how to reproduce the issue, example code or content and error messages?

**Comment by MartinR4838** [comment]
Sorry,

It seems that I have double quotes on wrong position.

**Comment by MartinR4838** [comment]
Whole CLI is used by Python´s script, latest version is scraped/downloaded from your github

  eark_cli_syntax = (str('java -jar ' + path + '/modules' + '/commons-ip2-cli-' + str(commons_ip) + '.jar' +
                           ' create -m "' + metadata_dir + 'dc.xml;dc" -ms ' + metadata_dir + 'dc.xsd -r "' + data_path
                           + ';Geospatial Data;representation1"' + ' -sid ' + str(geosip) + ' -doc ' + doc_dir +
                           ' -p ' + str(cz_sip) + ' -san ' + str(agent) + ' -aid ' + str(agent_uuid)))

**Comment by luis100** [comment]
@MartinR4838 can you share the output of the tool with the error report?

**Comment by MartinR4838** [comment]
You can close it.
