### ISSUE TITLE
Does not validate root METS against SIP/AIP specification when no representation METS exists

### ISSUE THREAD

**Issue by ThomasEdvardsen** [keeps/commons-ip#207]
Using cli-2.4.0 the `IpType` is not set on `metsValidatorState` for root METS when there is no representation METS. If there is a representation METS the value for the `IpType` is set in the `validateSubMets` method, and used for the root METS as well.

From the validateSubMets method:
```
metsValidatorState.setMets(instatiateMets.instatiateMetsFile());
metsValidatorState.setIpType(metsValidatorState.getMets().getMetsHdr().getOAISPACKAGETYPE());
setupMetsValidatorState(entry.getKey(), isZip, false);
validateComponents();
```

From the validateRootMets method:
```
metsValidatorState.setMetsPath(earksipPath.toString());
metsValidatorState.setMetsName(ipPath);
metsValidatorState.setIsRootMets(true);

metsValidatorState.setMets(metsRoot.instatiateMetsFile());
validateComponents();
```

The line `metsValidatorState.setIpType` method must be set in the validateRootMets as well, to validate against the SIP/AIP specification.

If the `IpType` is not set, the `validateIpTypeExtendedComponents` method are not able to specify extended components.

**Comment by hmiguim** [comment]
done at 37ad378a135737556ae23816db66bbdc6a1b518e
