### ISSUE TITLE
Improve Zip related functions (if 2 entries are added to Zip with the same "ZIP path", commons-ip crashes)

### ISSUE THREAD

**Issue by sleroux-keep** [keeps/commons-ip#21]
2 fixes possible:
- catch the duplicated entry exception and ignore
- replace List<ZipEntryInfo> with Map<String,ZipEntryInfo> (the key is the zip path)

**Comment by sleroux-keep** [comment]
Fixed @ 67672e0a319ecae41d4097039974805564e5c58a

**Comment by hsilva-keep** [comment]
Done since 67672e0a319ecae41d4097039974805564e5c58a (and merged into master).
