### ISSUE TITLE
Release process is not updating the version in the pom

### ISSUE THREAD

**Issue by 006627** [keeps/commons-ip#238]
The source code attached in release 2.5.0 is still version 2.4.0-SNAPSHOT, look for possible solutions with github actions.

Ideally, the release process should update the versions in the pom before creating the release, so that the attached source code has the correct version.

If it is not possible with github action, the process must be done with scripts and there must be instructions on how to create the release for this project

**Comment by hmiguim** [comment]
Script to increment minor version: https://gist.github.com/siddharthkrish/32072e6f97d7743b1a7c47d76d2cb06c

Github actions to commit and push: https://github.com/marketplace/actions/github-commit-push

**Comment by hmiguim** [comment]
DEV_NOTES and scripts were added to prepare the next release.
