### ISSUE TITLE
What is the purpose of IANA Media Types list?

### ISSUE THREAD

**Issue by ThomasEdvardsen** [keeps/commons-ip#249]
We are trying to create an eArchive SIP with wav-files in it. These files are given the mimetype "application/octet-stream" in the METS file and not "audio/x-wav" as expected, due to not being on the IANA Media Types list.

What is the purpose of IANA Media Types list?

**Comment by luis100** [comment]
Hi @ThomasEdvardsen, the best forum for this question would be the [CSIP spec github project](https://github.com/DILCISBoard/E-ARK-CSIP/issues/), but I guess that if you are setting a MIME type, it should follow the controlled vocabullary standard, which in the case of MIME's would be the IANA Media Type list. I do understand this is not optimal as the standard list lacks many of the commonly used formats. But, anyway, the MIME types in the METS file are not widely used. In RODA, we do not use them at all, we always do automatic file format identification (using Siegfried and PRONOM database) and set the formats (MIME type and PRONOM id) in the PREMIS metadata, kept in the metadata/preservation folder for each representation.

**Comment by ThomasEdvardsen** [comment]
Thanks @luis100. 
I found an issue on this, so hopefully it would be changed. 
https://github.com/DILCISBoard/E-ARK-CSIP/issues/704

**Comment by luis100** [comment]
@ThomasEdvardsen not sure if you are aware but in Commons-IP you can extend that base list: https://github.com/keeps/commons-ip?tab=readme-ov-file#extend-list-of-iana-media-types

**Comment by ThomasEdvardsen** [comment]
I found it after i created this issue ;)
