### ISSUE TITLE
Question regarding AIP

### ISSUE THREAD

**Issue by jalshorji** [keeps/commons-ip#282]
Is there a way to parse org.roda.core.data.v2.ip.AIP into org.roda_project.commons_ip2.model.impl.eark.AIP?

**Comment by luis100** [comment]
I don't think so, there are fundamental differences on how each one is used.

The commons-ip AIP is used for validating E-ARK AIPs.

The RODA's AIP is a specific implementation in RODA which has more complexity and features, like permissions, indexing considerations, and is tied to storage implementations.

In hindsight, they should be more compatible, but the RODA AIP existed before E-ARK AIPs came along, so there is a legacy that makes them incompatible.

But, an E-ARK AIP can very easily be transformed in a E-ARK SIP, and there are methods to create an RODA AIP from an E-ARK SIP. Check this utility class: https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/java/org/roda/core/plugins/base/ingest/EARKSIPToAIPPluginUtils.java
