### ISSUE TITLE
E-ARK ingestion fails when packaged item name contains plus (+) symbol

### ISSUE THREAD

**Issue by luis100** [keeps/commons-ip#29]
Details at: https://github.com/keeps/roda/issues/1315

**Comment by david-russo** [comment]
Hey guys, has there been any progress on this issue?

**Comment by luis100** [comment]
Just tested it and it seems it is still a problem, at least with the commons-ip version used in RODA-in 2.2.0. @hsilva-keep any possibility to do a quick fix here? It seems the problem is URL escaping.

**Comment by hsilva-keep** [comment]
Fixed by 8a11c2617a49f49cbc4f035997e5878b638a75e0
