### ISSUE TITLE
Different types of administrative metadata

### ISSUE THREAD

**Issue by mhalkiad** [keeps/commons-ip#32]
Hi all,
is it possible to have different types of administrative metadata such as  <techMD>, <rightsMD>, <sourceMD> except for <digiprovMD> in the METS file? 

Thank you in advance.
Regards

**Comment by jmaferreira** [comment]
Dear @mhalkiad,

I believe your question is mostly about the EARK SIP specification and not so much about the Commons-IP. In that regard I recommend you submit your question to the eArchiving service desk at https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/Support+eArchiving

Best regards
