### ISSUE TITLE
Insert embedded descriptive metadata?

### ISSUE THREAD

**Issue by mhalkiad** [keeps/commons-ip#33]
Hi all,
how to add embedded descriptive metadata into EARKSIP METS file? I am using IPDescriptiveMetadata class.

Thank you in advance.
Regards.

**Comment by hsilva-keep** [comment]
@mhalkiad at the moment it is not possible to do it in commons-ip. METS allows it, but it has been decided by the Common Specification for Information Packages (https://earkcsip.dilcis.eu/) that referencing will be preferred over embedding (https://earkcsip.dilcis.eu/#53-use-of-mets), therefore it has not been implemented support for embedding.
