### ISSUE TITLE
Compliance with CSIP 2.0.4

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/commons-ip#42]
- Talk to Kuldar to know the deadlines of this action
- Talk to Kuldar to make sure the version we should be compatible with
- Talk to Carl to know where the test corpora is
- Talk to Carl to know the format of the output

Specifications are published at https://dilcis.eu/specifications/common-specification

**Comment by JoaoGomes2110** [comment]
Compliance issues:

- [ ] CSIP1 - The mets/@OBJID attribute is mandatory, its value is a string identifier for the METS document. For the package METS document, this should be the name/ID of the package, i.e. the name of the package root folder.
For a representation level METS document this value records the name/ID of the representation, i.e. the name of the top-level representation folder.

**Comment by JoaoGomes2110** [comment]
- #47
- #48
- #49
- #50
- #51
