### ISSUE TITLE
Compliance with SIP 2.0.4

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/commons-ip#43]
- Talk to Kuldar to know the deadlines of this action
- Talk to Kuldar to make sure the version we should be compatible with
- Talk to Carl to know where the test corpora is
- Talk to Carl to know the format of the output

Specification is published at https://dilcis.eu/specifications/sip

**Comment by luis100** [comment]
Project with test corpus: https://github.com/DILCISBoard/eark-ip-test-corpus
There is a branch with each requisite.

**Comment by JoaoGomes2110** [comment]
- #52
