### ISSUE TITLE
How is compliance with CSIPSTR10 established

### ISSUE THREAD

**Issue by carlwilson** [keeps/commons-ip#74]
This test always seems to fail, I'm not sure what's needed to satisfy it. For example why does the attached package fail CSIPSTR10?
[valid-ip.zip](https://github.com/keeps/commons-ip/files/7418096/valid-ip.zip)

**Comment by JoaoGomes2110** [comment]
Fixed https://github.com/keeps/commons-ip/releases/edit/2.0.0
