### ISSUE TITLE
Discrepancies between report results

### ISSUE THREAD

**Issue by carlwilson** [keeps/commons-ip#85]
When I try to validate this package:

[valid.zip](https://github.com/keeps/commons-ip/files/7474964/valid.zip)

using the `-r eark` flag I don't seem to get all of the error messages. I first thought that the problem was one of the status flag not getting set to VALID properly but that's not the case. The package is invalid but the error list reported with the `-r eark` flag is missing key failure messages. Here's the output for normal reporting: 
[valid.zip_validation-report_2021-11-04_1.txt](https://github.com/keeps/commons-ip/files/7474970/valid.zip_validation-report_2021-11-04_1.txt)
and this is the output with `-r eark` set 
[valid.zip_validation-report_2021-11-04_2.txt](https://github.com/keeps/commons-ip/files/7474983/valid.zip_validation-report_2021-11-04_2.txt)
. While I don't expect to see skipped tests or passed ones there are a bunch of failures in the first output that aren't in the second.

**Comment by JoaoGomes2110** [comment]
Hi @carlwilson i forgot to add a condition in the calculation of the error in the case of the -r eark option. I have corrected the problem.
